name: proxy-ci
on: workflow_dispatch
jobs:
  build:
    name: "Deploy To Dev"
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: 'actions/checkout@v3'
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/762356276584/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 's1-679@absolute-gantry-344218.iam.gserviceaccount.com'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
      - name: Create API bundle
        run: zip -r proxy.zip . -i apiproxy
      - name: 'Upload Proxy'
        run: |-
          curl https://apigee.googleapis.com/v1/organizations/absolute-gantry-344218/apis?action=import&name=hello-world \
            --header "Authorization: Bearer ${{ steps.auth.outputs.access_token }}" \
            --header "Content-Type: multipart/form-data" \
            -F "file=@proxy.zip" \
